import { Geist, Geist_Mono } from 'next/font/google'; // ሁለት ፎንት import ሲሆን
import './globals.css'; //Geist_Mono ግሎባል የሆን css ነው
import Header from '../component/Header'; //Header ኮምፖነንት
import Footer from '../component/Footer'; //Footer ኮምፖነንት
const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full grid grid-rows-3 gap-[10vw]">
        <header className="bg-grey-100 text-center">
          <Header />
        </header>

        {children}

        <footer className="bg-yellow-500 text-black-600 text-center">
          <Footer />
        </footer>
      </body>
    </html>
  );
}
